export const FORM_FIELDS = {
  EMAIL: 'email',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirmPassword',
  CURRENT_PASSWORD: "currentPassword",
  FULL_NAME: 'fullName',
  USER_NAME: "userName",
  PHONE: "phone",
  ADDRESS: "address",
  DESCRIPTION: "description",
  CITY: "city",
  COUNTRY: "country",
  DOB: 'dob',
  OTP: 'otp',
  CONTACT_NO: "phone",
  LOCATION: "location",
  TAX: "tax",
  DOCUMENTATION: "documentation",
  PROPERTY_TITLE: "propertyTitle",
  PROPERTY_IMAGE: "propertyImage",
  FLOOR_NUMBER: "floorNumber",
  APARTMENT_NUMBER: "apartmentNumber",
  PROPERTY_SIZE:"propertySize",
  LOCATION:"location",
  KEY_LOCATION:"keyLocation",
  KEY_PASSWORD:"keyPassword"
};

export const FORM_LABELS = {
  [FORM_FIELDS.EMAIL]: 'Email Address',
  [FORM_FIELDS.PASSWORD]: 'Password',
  [FORM_FIELDS.CONFIRM_PASSWORD]: "Confirm Password",
  [FORM_FIELDS.CURRENT_PASSWORD]: 'Current Password',
  [FORM_FIELDS.FULL_NAME]: 'Full Name',
  [FORM_FIELDS.USER_NAME]: "User Name",
  [FORM_FIELDS.PHONE]: "Number",
  [FORM_FIELDS.ADDRESS]: "Address",
  [FORM_FIELDS.DESCRIPTION]: "Description",
  [FORM_FIELDS.CITY]: "City",
  [FORM_FIELDS.COUNTRY]: "Country",
  [FORM_FIELDS.DOB]: 'Date of Birth',
  [FORM_FIELDS.CONTACT_NO]: "Contact Number",
  [FORM_FIELDS.LOCATION]: "Location",
  [FORM_FIELDS.TAX]: "Tax ID (Add your tax id for buying wholesaling products)",
  [FORM_FIELDS.DOCUMENTATION]: "Tax ID (Add your tax id for buying wholesaling products)",
  [FORM_FIELDS.PROPERTY_TITLE]: "Property title",
  [FORM_FIELDS.PROPERTY_IMAGE]: "Property Image",
  [FORM_FIELDS.FLOOR_NUMBER]: "Floor",
  [FORM_FIELDS.APARTMENT_NUMBER]: "Apartment Number",
  [FORM_FIELDS.PROPERTY_SIZE]: "Property Size",
  [FORM_FIELDS.LOCATION]:"Location"
};

export const FORM_PLACEHOLDERS = {
  [FORM_FIELDS.EMAIL]: 'Enter your email address',
  [FORM_FIELDS.PASSWORD]: 'Enter your password',
  [FORM_FIELDS.CONFIRM_PASSWORD]: "Enter your Confirm Password",
  [FORM_FIELDS.CURRENT_PASSWORD]: "Enter your Current Password",
  [FORM_FIELDS.FULL_NAME]: 'Enter your full name',
  [FORM_FIELDS.USER_NAME]: 'Enter your username',
  [FORM_FIELDS.DOB]: 'Select your date of birth',
  [FORM_FIELDS.CONTACT_NO]: "+99 54196 418164",
  [FORM_FIELDS.DOCUMENTATION]: "Message",
  [FORM_FIELDS.LOCATION]: "New York, NY, USA .2 a...",
  [FORM_FIELDS.TAX]: "1485 482895632 86885938",
  [FORM_FIELDS.DOCUMENTATION]: "1485 482895632 86885938",
  [FORM_FIELDS.PROPERTY_TITLE]: "Le Central",
  [FORM_FIELDS.PROPERTY_IMAGE]: `➕  Add photos`,
  [FORM_FIELDS.FLOOR_NUMBER]: "3rd",
  [FORM_FIELDS.APARTMENT_NUMBER]:"301",
  [FORM_FIELDS.PROPERTY_SIZE]:"50 m2",
  [FORM_FIELDS.LOCATION]:"France",
  [FORM_FIELDS.KEY_LOCATION]:"e.g. B. Berlin or",
  [FORM_FIELDS.KEY_PASSWORD]:"******"
};