import { IMAGE_COMPONENTS } from "../assets/image.index";

/**
 * cleanerDetailsData
 * status: "Accept", "In Progress"
 */

export const AllJobsData = [
  // ✅ Accept data 1
  {
    id: 1,
    status: "Accept",
    date: "Samedi 30th December",
    day: "Saturday",
    city: "Lisbon",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Premium cleaning service with focus on eco-friendly products and attention to detail.",
    country: "Portugal",
    area: "70–120 m²",
    beds: 3,
    bedrooms: 3,
    bathrooms: 2,
    buildingName: "Lisbon Residence",
    property_type: "Apartment",
    lock_system: "Manual Key",
    timeSlot: "10:00-16:00",
    duration: "3Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: true,
    cleanerName: "Ana",
    price: 75.0,
    cleanerImage: "https://i.pravatar.cc/150?img=45",
    cleaner_request: [
      { id: 501, profile_img: "https://i.pravatar.cc/150?img=51", name: "Lara Costa" },
      { id: 502, profile_img: "https://i.pravatar.cc/150?img=52", name: "Tiago Silva" },
    ],
    general_types: [{ id: 1, name: "Full Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Dusting" }],
    kitchen_room: [{ id: 1, name: "Dish Washing" }],
    completed_tasks: [],
  },

  // ✅ Accept data 2
  {
    id: 2,
    status: "Accept",
    date: "Dimanche 31st December",
    day: "Sunday",
    city: "Barcelona",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Luxury apartment cleaning with attention to all rooms and premium services.",
    country: "Spain",
    area: "80–140 m²",
    beds: 4,
    bedrooms: 4,
    bathrooms: 3,
    buildingName: "Barcelona Heights",
    property_type: "Villa",
    lock_system: "Keypad",
    timeSlot: "09:00-17:00",
    duration: "4Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: true,
    cleanerName: "Miguel",
    price: 120.0,
    cleanerImage: "https://i.pravatar.cc/150?img=55",
    cleaner_request: [
      { id: 601, profile_img: "https://i.pravatar.cc/150?img=56", name: "Sofia Lopez" },
    ],
    general_types: [{ id: 1, name: "Deep Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Mopping" }],
    kitchen_room: [{ id: 1, name: "Appliance Cleaning" }],
    completed_tasks: [],
  },

  // ✅ In Progress data 1
  {
    id: 3,
    status: "InProgress",
    date: "Lundi 1st January",
    day: "Monday",
    city: "Amsterdam",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Ongoing cleaning service for central city apartment with partial tasks completed.",
    country: "Netherlands",
    area: "60–100 m²",
    beds: 2,
    bedrooms: 2,
    bathrooms: 1,
    buildingName: "Amsterdam Central",
    property_type: "Apartment",
    lock_system: "Smart Lock",
    timeSlot: "08:00-12:00",
    duration: "2Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: false,
    cleanerName: "Jan",
    price: 60.0,
    cleanerImage: "https://i.pravatar.cc/150?img=60",
    cleaner_request: [
      { id: 701, profile_img: "https://i.pravatar.cc/150?img=61", name: "Eva Jansen" },
    ],
    general_types: [{ id: 1, name: "Standard Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Vacuum" }],
    kitchen_room: [{ id: 1, name: "Dish Washing" }],
    completed_tasks: [],
  },

  // ✅ Accept duplicate for 7 items
  {
    id: 4,
    status: "Accept",
    date: "Mardi 2nd January",
    day: "Tuesday",
    city: "Florence",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Standard apartment cleaning with attention to eco-friendly materials.",
    country: "Italy",
    area: "50–90 m²",
    beds: 2,
    bedrooms: 2,
    bathrooms: 1,
    buildingName: "Florence Residence",
    property_type: "Apartment",
    lock_system: "Manual Key",
    timeSlot: "09:00-13:00",
    duration: "3Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: true,
    cleanerName: "Luca",
    price: 65.0,
    cleanerImage: "https://i.pravatar.cc/150?img=70",
    cleaner_request: [
      { id: 801, profile_img: "https://i.pravatar.cc/150?img=71", name: "Elena Rossi" },
    ],
    general_types: [{ id: 1, name: "Full Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Dusting" }],
    kitchen_room: [{ id: 1, name: "Dish Washing" }],
    completed_tasks: [],
  },

  // ✅ In Progress duplicate
  {
    id: 5,
    status: "InProgress",
    date: "Mercredi 3rd January",
    day: "Wednesday",
    city: "Brussels",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Ongoing cleaning with focus on kitchen and living room areas.",
    country: "Belgium",
    area: "60–110 m²",
    beds: 3,
    bedrooms: 3,
    bathrooms: 2,
    buildingName: "Brussels Central",
    property_type: "Apartment",
    lock_system: "Keypad",
    timeSlot: "08:00-14:00",
    duration: "3Hours 30Min",
    equipmentProvided: true,
    laundryIncluded: false,
    cleanerName: "Thomas",
    price: 85.0,
    cleanerImage: "https://i.pravatar.cc/150?img=80",
    cleaner_request: [
      { id: 901, profile_img: "https://i.pravatar.cc/150?img=81", name: "Emma Van Dam" },
    ],
    general_types: [{ id: 1, name: "Standard Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Vacuum" }],
    kitchen_room: [{ id: 1, name: "Dish Washing" }],
    completed_tasks: [],
  },

  // ✅ Accept extra
  {
    id: 6,
    status: "Accept",
    date: "Jeudi 4th January",
    day: "Thursday",
    city: "Madrid",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Premium villa cleaning with full attention to bathrooms and kitchen.",
    country: "Spain",
    area: "90–150 m²",
    beds: 4,
    bedrooms: 4,
    bathrooms: 3,
    buildingName: "Madrid Heights",
    property_type: "Villa",
    lock_system: "Smart Lock",
    timeSlot: "09:00-18:00",
    duration: "5Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: true,
    cleanerName: "Miguel",
    price: 130.0,
    cleanerImage: "https://i.pravatar.cc/150?img=85",
    cleaner_request: [
      { id: 1001, profile_img: "https://i.pravatar.cc/150?img=86", name: "Isabella Garcia" },
    ],
    general_types: [{ id: 1, name: "Deep Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Mopping" }],
    kitchen_room: [{ id: 1, name: "Appliance Cleaning" }],
    completed_tasks: [],
  },

  // ✅ In Progress extra
  {
    id: 7,
    status: "InProgress",
    date: "Vendredi 5th January",
    day: "Friday",
    city: "Vienna",
    image: IMAGE_COMPONENTS.archiveImage,
    propertyImage: IMAGE_COMPONENTS.propertyDetailsImage,
    images: [IMAGE_COMPONENTS.propertyImage],
    description: "Cleaning ongoing for a central apartment with attention to living room and bedroom.",
    country: "Austria",
    area: "55–100 m²",
    beds: 2,
    bedrooms: 2,
    bathrooms: 1,
    buildingName: "Vienna Central",
    property_type: "Apartment",
    lock_system: "Manual Key",
    timeSlot: "08:00-12:00",
    duration: "3Hours 00Min",
    equipmentProvided: true,
    laundryIncluded: false,
    cleanerName: "Anna",
    price: 70.0,
    cleanerImage: "https://i.pravatar.cc/150?img=90",
    cleaner_request: [
      { id: 1101, profile_img: "https://i.pravatar.cc/150?img=91", name: "Lukas Meyer" },
    ],
    general_types: [{ id: 1, name: "Standard Cleaning" }],
    bed_room: [{ id: 1, name: "Bed Making" }],
    living_room: [{ id: 1, name: "Vacuum" }],
    kitchen_room: [{ id: 1, name: "Dish Washing" }],
    completed_tasks: [],
  },
];
